language: go

sudo: required

go:
  - 1.10.x
  - tip

before_install:
  # Setup dependency management tool
  - curl -L -s https://github.com/golang/dep/releases/download/v0.3.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure

script:
  - go test ./...

# TODO: Is this the right slack channel?
notifications:
  slack: myndshfttech:eye5HmlClH9OThrY2xqdn3CN
  email: false

matrix:
  allow_failures:
    - go: tip
